version: '3'
services:
  web_gui:
      build:
        context: .
        dockerfile: docker-compose/Dockerfile
      links:
          - reductus
      ports:
          - "8000:80"

  reductus:
      build: 
        context: .
        dockerfile: docker-compose/gevent/Dockerfile
      volumes:
        - ./web_gui/testdata:/data
      links:
          - redis
      expose:
          - "8001"
          
  redis:
      image: redis
      expose:
          - "6379"
